[project]
name = "aku"
version = "0.2.6"
description = "An interactive annotation-driven ArgumentParser generator"
readme = "README.md"
requires-python = ">=3.10"
dependencies = []

[dependency-groups]
dev = [
    "hypothesis>=6.142.5",
    "pytest>=8.4.2",
]
